# Generated by Django 6.0.3 on 2026-03-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Articulo",
        ),
        migrations.RenameModel(
            old_name="Author",
            new_name="Autor",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Categoria",
        ),
    ]
